[package]
name = "rolling_drone"
version = "0.1.0"
edition = "2021"

[dependencies]
crossbeam-channel = "0.5.13"
rand = "0.9.0-beta.1"
wg_2024 = { git = "https://github.com/WGL-2024/WGL_repo_2024.git", features = ["serialize", "debug"]}